# frozen_string_literal: true

# default
task default: %i[spec rubocop]

# clean/clobber
require "rake/clean"

CLEAN.include("coverage", ".rspec_status", ".yardoc")
CLOBBER.include("doc/api", "pkg")

# spec
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

# rubocop
require "rubocop/rake_task"

RuboCop::RakeTask.new do |t|
  # Avoid loading config from project root
  t.options = %w[--config .rubocop.yml]
end

# doc
require "yard"

YARD::Rake::YardocTask.new(:doc)
