AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - foxtail-runtime/**/*
    - foxtail-tools/**/*
    - vendor/**/*
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/security.yml
    - config/cops/style.yml

Style/DocumentationMethod:
  Exclude:
    - 'Rakefile'

Style/TopLevelMethodDefinition:
  Exclude:
    - 'Rakefile'
