---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
  - bin/**/*
  - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.4
  UseCache: true
inherit_mode:
  merge:
  - Exclude
plugins:
- rubocop-performance
- rubocop-rake
- rubocop-rspec
require: []
inherit_from:
- .rubocop_todo.yml
- .rubocop/bundler.yml
- .rubocop/gemspec.yml
- .rubocop/layout.yml
- .rubocop/lint.yml
- .rubocop/metrics.yml
- .rubocop/migration.yml
- .rubocop/naming.yml
- .rubocop/performance.yml
- .rubocop/rspec.yml
- .rubocop/rake.yml
- .rubocop/security.yml
- .rubocop/style.yml

# Disable Metrics cops for parser-related files and error handling
# Parser implementations inherently have complex methods and classes due to the nature of parsing
# Error handling also requires complex case statements for different error codes
Metrics/AbcSize:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

Metrics/BlockNesting:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'
    - 'lib/foxtail/errors.rb'

# Disable Naming/MethodParameterName for parser-related files
# Parser implementations often use short parameter names for brevity and clarity
Naming/MethodParameterName:
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/stream.rb'

# Disable RSpec cops for complex parser tests
# Parser tests often require multiple expectations to verify complex parsing logic
# FTL parsing tests need to validate multiple aspects of the parsed AST structure
RSpec/ExampleLength:
  Exclude:
    - 'spec/foxtail/parser_spec.rb'
    - 'spec/foxtail/parser/reference/*.rb'
    - 'spec/foxtail/parser/structure/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/foxtail/parser_spec.rb'
    - 'spec/foxtail/parser/reference/*.rb'
    - 'spec/foxtail/parser/structure/*.rb'

# Configure SpecFilePathFormat to handle our specific file structure
# The parser tests are organized by feature/structure rather than by class/method
RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/foxtail/parser/reference/*.rb'
    - 'spec/foxtail/parser/structure/*.rb'

# Disable Style/DocumentationMethod for implementation details
# These methods are implementation details and don't need documentation
Style/DocumentationMethod:
  RequireForNonPublicMethods: false
  Exclude:
    - 'lib/foxtail/parser.rb'
    - 'lib/foxtail/ast/base.rb'
    - 'lib/foxtail/errors.rb'
    - 'lib/foxtail/stream.rb'
