# frozen_string_literal: true

require "rake/clean"

CLEAN.include("coverage", ".rspec_status", ".yardoc")
CLOBBER.include("doc/api", "pkg")

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"
RuboCop::RakeTask.new(:rubocop) do |t|
  t.patterns = [
    "exe/*",
    "lib/**/*.rb",
    "spec/**/*.rb",
    "*.gemspec"
  ]
end

require "yard"
YARD::Rake::YardocTask.new(:doc)

task default: %i[spec rubocop]
