#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/fantail"
require "dry/cli"

begin
  Dry::CLI.new(Fantail::CLI).call
rescue Fantail::CLI::Error => e
  warn e.message
  exit 1
end
