#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/foxtail"
require "dry/cli"

begin
  Dry::CLI.new(Foxtail::CLI).call
rescue Foxtail::CLI::Error => e
  warn e.message
  exit 1
end
